test: get ci validation from libdatadog

diff --git a/.github/workflows/rs_ci.yml b/.github/workflows/rs_ci.yml
--- a/.github/workflows/rs_ci.yml
+++ b/.github/workflows/rs_ci.yml
@@ -137,14 +137,13 @@ jobs:
       - uses: mozilla-actions/sccache-action@v0.0.5
       - working-directory: bottlecap
         run: cargo nextest run --workspace
-      - run: cargo bundle-licenses --format yaml --output ci-license-check.yml --previous LICENSE-3rdparty.yml --check-previous
 
   format:
     name: Format
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-22.04, macos-latest]
+        os: [ ubuntu-22.04, macos-latest ]
     steps:
       - uses: actions/checkout@v4
       - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
@@ -153,3 +152,59 @@ jobs:
           cache: false
       - working-directory: bottlecap
         run: cargo fmt --all -- --check
+
+  # todo: fix upstream warnings; from the readme:
+  # The most common cause of missing licenses seems to be workspaces that
+  # don't include forward their license files. Go to the repo for the
+  # workspace and copy the relevant files from there.
+  # A package license may receive a confidence warning stating that
+  # cargo-bundle-licenses is "unsure" or "semi" confident. This means that
+  # when the found license was compared to a template license it was found to
+  # have diverged in more than a few words. You should verify that the licence
+  #  text is in fact correct in these cases.
+  #
+  # If this job fails, you probably need to regenerate the license, e.g.
+  # CARGO_HOME=/tmp/dd-cargo cargo bundle-licenses --format yaml --output LICENSE-3rdparty.yml
+  license-3rdparty:
+    runs-on: ubuntu-latest
+    name: "Valid LICENSE-3rdparty.yml"
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v4
+      - run: stat LICENSE-3rdparty.yml
+      - name: Cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.cargo/registry/
+            ~/.cargo/git/db/
+            ~/.cargo/bin/
+            ~/.cargo/.crates.toml
+          # cache key contains current version of cargo-bundle-licenses
+          # when upstream version is updated we can bump the cache key version,
+          # to cache the latest version of the tool
+          key: "v1-2.0.0"
+      # cargo-bundle-licenses v2.0 doesn't understand path differences due to
+      # sparse vs git index, so force git.
+      - run: mkdir -p .cargo && printf "[registries.crates-io]\nprotocol = \"git\"\n" > .cargo/config.toml
+      - run: cargo install cargo-bundle-licenses
+      - name: "Generate new LICENSE-3rdparty.yml and check against the previous"
+        env:
+          CARGO_HOME: "/tmp/dd-cargo"
+        run: |
+          # Run cargo bundle-licenses without directly checking against a previous snapshot
+          cargo bundle-licenses \
+            --format yaml \
+            --output /tmp/CI.yaml
+
+          # Normalize the paths in both files to ignore registry differences
+          sed -E 's/(registry\/src\/)[^\/]+/\1normalized_path/g' /tmp/CI.yaml > /tmp/CI_normalized.yaml
+          sed -E 's/(registry\/src\/)[^\/]+/\1normalized_path/g' LICENSE-3rdparty.yml > /tmp/LICENSE-3rdparty_normalized.yml
+
+          # Now perform the diff on the normalized files
+          if ! diff /tmp/CI_normalized.yaml /tmp/LICENSE-3rdparty_normalized.yml; then
+            echo "Differences detected."
+            exit 1
+          fi
+
+          echo "No differences found."
